### PR TITLE
improve Gradio streaming audio playback

### PR DESCRIPTION
**Pull request by Mereithhh**
- Optimize audio chunk sizes with progressive growth strategy
- Adjust audio processing logic for smoother real-time playback

### CODE REVIEW

**Comment by sixsixcoder** [comment]
How do I evaluate the performance improvement after modifying the code?

**Review by zRzRzRzRzRzRzR — APPROVED** [review]
The code runs, but please check if it works as expected.
https://github.com/user-attachments/assets/ca4b5b35-e5ad-44d5-a83b-bc1625bc6ef8

**Comment by Mereithhh** [comment]
> How do I evaluate the performance improvement after modifying the code?

This PR mainly improves the issues of glitches and stuttering during playback. Enter any query, and you can see the difference in performance by comparing the results before and after the code changes.

**Comment by Mereithhh** [comment]
In Gradio’s streaming playback, audio is converted to AAC format, and the AAC encoder pads frames at the end. If padding occurs while speech is ongoing, it can cause noticeable stuttering. The latest code improves this issue by shifting the seams to silent sections, reducing the stuttering.

img_v3_02g7_0c3c1177-06f6-4281-a857-bf75ecceddeg

**Comment by NanYANG2015** [comment]
> * Optimize audio chunk sizes with progressive growth strategy
> * Adjust audio processing logic for smoother real-time playback

What is the motivation for gradually increasing the audio chunk size?
Is it because considering the inference speed of LLM, the 26 audio tokens inferred for the first time correspond to about 2s of audio, which takes 2s to play, and supports the subsequent increase of the audio chunk size, thereby reducing the number of flow matching inferences, and reducing the discontinuity between the generated multiple audio chunks?

If the first audio chunk size increases from 10 to 25, will the first delay increase?

**Comment by Mereithhh** [comment]
> > * Optimize audio chunk sizes with progressive growth strategy
> > * Adjust audio processing logic for smoother real-time playback
> 
> What is the motivation for gradually increasing the audio chunk size? Is it because considering the inference speed of LLM, the 26 audio tokens inferred for the first time correspond to about 2s of audio, which takes 2s to play, and supports the subsequent increase of the audio chunk size, thereby reducing the number of flow matching inferences, and reducing the discontinuity between the generated multiple audio chunks?
> 
> If the first audio chunk size increases from 10 to 25, will the first delay increase?

Under the premise that the speed of audio generation exceeds the speed of playback, reducing the number of inferences helps to decrease the occurrence of bad cases. Additionally, when the synthesis speed is sufficient, increasing the length of the audio will lead to a lot of redundancy, and there will not be a need for as many inferences.

This modification will indeed affect some initial response latencies, especially if your LLM inference speed is insufficient. However, in the context of this demo, the focus is more on the synthesis quality. In a production environment, you may need to explore the best practices for this parameter on your own.

**Comment by ddlBoJack** [comment]
Is the vocoder updated? I mean the chunk size is still 10 when training the flow-matching, or bigger?

**Pull request merged**
